# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'YellowPod' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for YellowPod
  pod 'Alamofire', '~> 4.5'
  pod 'SDWebImage', '~>4.0'
  pod 'SwiftyJSON'
  pod 'DefaultsKit'
  pod 'Bugle'
  pod 'ReachabilitySwift'

  target 'YellowPodTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'YellowPodUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
